### ISSUE TITLE
Error when trying to install 1.1.0

### ISSUE THREAD

**Issue by automartin5000** [DataDog/datadog-cdk-constructs#136] opened 2022-12-16 17:37 UTC
## Expected Behavior
Installs correctly

## Actual Behavior
Error on `npm install`
```
npm ERR! code 1
npm ERR! path /Users/martin/projects/es-cdk-constructs/node_modules/datadog-cdk-constructs-v2
npm ERR! command failed
npm ERR! command sh -c -- npx projen preinstall
npm ERR! Unknown command: preinstall
```

## Steps to Reproduce the Problem

  1. Change package.json to `"datadog-cdk-constructs-v2": "^1.1.0",`
  2. Run `npm install`
  3. Get error

## Specifications

  - Datadog Lambda Layer version: N/A
  - Node version: 18.12.1
  
## Stacktrace
  
  ```
npm ERR! path /Users/martin/projects/es-cdk-constructs/node_modules/datadog-cdk-constructs-v2
npm ERR! command failed
npm ERR! command sh -c -- npx projen preinstall
npm ERR! Unknown command: preinstall
  ```

**Comment by sfirrin** [comment] 2022-12-16 18:55
Hi @automartin5000 thanks for raising this and sorry for the issue

I'm working on reverting what appears to be the cause and creating another release now

**Comment by sfirrin** [comment] 2022-12-16 21:13
Hi again @automartin5000, thanks again for opening this issue. 

This should be fixed now in https://github.com/DataDog/datadog-cdk-constructs/releases/tag/v2-1.2.0, please try it out.

**Closed by sfirrin** 2022-12-16 21:13 UTC

**Comment by automartin5000** [comment] 2022-12-17 21:32
@sfirrin Everything looks good including Node 18 support. Thanks!
