### ISSUE TITLE
Receiving logs and extended metrics but not traces

### ISSUE THREAD

**Issue by nacho-vazquez** [DataDog/datadog-cdk-constructs#240] opened 2023-12-13 04:10 UTC
## Expected Behavior

I should be able to see my lambda function traces.

## Actual Behavior

I see the logs and extended metrics like cold starts but not the traces.

## Steps to Reproduce the Problem

  1. Setup with SST
  1. Deploy
  1. Don't receive the traces
  
  I do receive the traces when using the `datadog-ci`
  
  Also, it works in dev/local mode but not in production mode.
  
  This is my setup
  
  ```ts
// datadog.stack.ts
import { App, StackContext } from 'sst/constructs';
import { Datadog } from 'datadog-cdk-constructs-v2';

// Don't enable locally
export const isDatadogEnabled = (app: App) => {
  return !app.local;
};

export const getDDApiKeySecretArn = (app: App) => {
  switch (app.stage) {
    case 'production':
      return 'arn:aws:secretsmanager:us-east-1:988079890905:secret:production/dataDogApiKeySecret-tfm4jg';
    case 'staging':
      return 'arn:aws:secretsmanager:us-east-1:863907625641:secret:staging/dataDogApiKeySecret-4bxQ4F';
    default:
      return 'arn:aws:secretsmanager:us-east-1:863907625641:secret:staging/dataDogApiKeySecret-4bxQ4F';
  }
};

export function DataDogStack({ stack, app }: StackContext) {
  const datadog = new Datadog(stack, 'datadog', {
    nodeLayerVersion: 102,
    extensionLayerVersion: 51,
    site: 'datadoghq.com',
    apiKeySecretArn: getDDApiKeySecretArn(app),
    env: app.stage,
    service: app.name,
    version:
      process.env['SEED_BUILD_SERVICE_SHA'] ||
      process.env['GITHUB_SHA'] ||
      '1.0.0',
  });

  return datadog;
}

  ```

```ts
// api.stack.ts
export function APIStack(ctx: StackContext) {
  const { bus } = use(EventsStack);
  const { db } = use(DatabaseStack);
  const { cognito } = use(CognitoStack);
  const dns = use(DNSStack);

  const api = new Api(ctx.stack, 'api', {
    customDomain: {
      domainName: dns.apiDomain,
      hostedZone: dns.apiZone.zoneName,
    },
    authorizers: {
      jwt: {
        type: 'user_pool',
        userPool: {
          id: cognito.userPoolId,
          clientIds: [cognito.userPoolClientId],
        },
      },
    },
    defaults: {
      authorizer: 'jwt',
      function: {
        bind: [db, bus],
        timeout: '60 seconds',
      },
    },
  });

  cognito.attachPermissionsForAuthUsers(ctx.stack, [api]);

  // Health
  api.addRoutes(ctx.stack, {
    'GET /health': {
      function: 'packages/functions/src/lib/health.handler',
      authorizer: 'none',
    },
  });

  if (isDatadogEnabled(ctx.app)) {
    const datadog = DataDogStack(ctx);
    datadog.addLambdaFunctions(ctx.stack.getAllFunctions());
  }

  ctx.stack.addOutputs({
    ApiEndpoint: api.customDomainUrl || api.url,
  });

  return { api };
}
```

## Specifications

  - Datadog Lambda Layer version: 102
  - Node version: 18
  
## Stacktrace
  
  ```
Validating props...
No value provided for flushMetricsToLogs, defaulting to true
Using extension version 51, metrics will be submitted via the extension
No value provided for addLayers, defaulting to true
No value provided for enableDatadogTracing, defaulting to true
No value provided for enableDatadogASM, defaulting to false
No value provided for enableMergeXrayTraces, defaulting to false
No value provided for injectLogContext, defaulting to true
No value provided for logLevel
No value provided for enableDatadogLogs, defaulting to true
No value provided for captureLambdaPayload, default to false
No value provided for sourceCodeIntegration, default to true
No value provided for redirectHandler, default to true
No value provided for grantSecretReadAccess, default to true
Using region: us-east-1
Applying layers to Lambda functions...
Using Node Lambda layer: arn:aws:lambda:us-east-1:464622532012:layer:Datadog-Node18-x:102
Generating construct Id for Datadog Lambda layer
Adding layer staging-aster-EventsStack/DatadogLayer-nodejs18.x-791ed699c5e1f177b63a98e804d08929694d2c6c523610390fe844ddfda7944b to Lambda: ${Token[TOKEN.1095]}
Using extension layer: arn:aws:lambda:us-east-1:464622532012:layer:Datadog-Extension-ARM:51
Generating construct Id for Datadog Extension layer
Adding layer staging-aster-EventsStack/DatadogExtension-791ed699c5e1f177b63a98e804d08929694d2c6c523610390fe844ddfda7944b to Lambda: ${Token[TOKEN.1095]}
Using Node Lambda layer: arn:aws:lambda:us-east-1:464622532012:layer:Datadog-Node18-x:102
Generating construct Id for Datadog Lambda layer
Adding layer staging-aster-EventsStack/DatadogLayer-nodejs18.x-791ed699c5e1f177b63a98e804d08929694d2c6c523610390fe844ddfda7944b to Lambda: ${Token[TOKEN.1131]}
Using extension layer: arn:aws:lambda:us-east-1:464622532012:layer:Datadog-Extension-ARM:51
Generating construct Id for Datadog Extension layer
Adding layer staging-aster-EventsStack/DatadogExtension-791ed699c5e1f177b63a98e804d08929694d2c6c523610390fe844ddfda7944b to Lambda: ${Token[TOKEN.1131]}
Using Node Lambda layer: arn:aws:lambda:us-east-1:464622532012:layer:Datadog-Node18-x:102
Generating construct Id for Datadog Lambda layer
Adding layer staging-aster-EventsStack/DatadogLayer-nodejs18.x-791ed699c5e1f177b63a98e804d08929694d2c6c523610390fe844ddfda7944b to Lambda: ${Token[TOKEN.1167]}
Using extension layer: arn:aws:lambda:us-east-1:464622532012:layer:Datadog-Extension-ARM:51
Generating construct Id for Datadog Extension layer
Adding layer staging-aster-EventsStack/DatadogExtension-791ed699c5e1f177b63a98e804d08929694d2c6c523610390fe844ddfda7944b to Lambda: ${Token[TOKEN.1167]}
Wrapping Lambda function handlers with Datadog handler...
Forwarder ARN not provided, no log group subscriptions will be added
Adding CDK Construct version tag: 1.10.0
Setting environment variables...
Adding datadog tags
Setting Datadog transport environment variables...
Adding source code integration...
Validating props...
No value provided for flushMetricsToLogs, defaulting to true
Using extension version 51, metrics will be submitted via the extension
No value provided for addLayers, defaulting to true
No value provided for enableDatadogTracing, defaulting to true
No value provided for enableDatadogASM, defaulting to false
No value provided for enableMergeXrayTraces, defaulting to false
No value provided for injectLogContext, defaulting to true
No value provided for logLevel
No value provided for enableDatadogLogs, defaulting to true
No value provided for captureLambdaPayload, default to false
No value provided for sourceCodeIntegration, default to true
No value provided for redirectHandler, default to true
No value provided for grantSecretReadAccess, default to true
Using region: us-east-1
Applying layers to Lambda functions...
Using Node Lambda layer: arn:aws:lambda:us-east-1:464622532012:layer:Datadog-Node18-x:102
Generating construct Id for Datadog Lambda layer
Adding layer staging-aster-EventsStack/DatadogLayer-nodejs18.x-791ed699c5e1f177b63a98e804d08929694d2c6c523610390fe844ddfda7944b to Lambda: ${Token[TOKEN.1233]}
Using extension layer: arn:aws:lambda:us-east-1:464622532012:layer:Datadog-Extension-ARM:51
Generating construct Id for Datadog Extension layer
Adding layer staging-aster-EventsStack/DatadogExtension-791ed699c5e1f177b63a98e804d08929694d2c6c523610390fe844ddfda7944b to Lambda: ${Token[TOKEN.1233]}
Wrapping Lambda function handlers with Datadog handler...
Forwarder ARN not provided, no log group subscriptions will be added
Adding CDK Construct version tag: 1.10.0
Setting environment variables...
Adding datadog tags
Setting Datadog transport environment variables...
Adding source code integration...
Validating props...
No value provided for flushMetricsToLogs, defaulting to true
Using extension version 51, metrics will be submitted via the extension
No value provided for addLayers, defaulting to true
No value provided for enableDatadogTracing, defaulting to true
No value provided for enableDatadogASM, defaulting to false
No value provided for enableMergeXrayTraces, defaulting to false
No value provided for injectLogContext, defaulting to true
No value provided for logLevel
No value provided for enableDatadogLogs, defaulting to true
No value provided for captureLambdaPayload, default to false
No value provided for sourceCodeIntegration, default to true
No value provided for redirectHandler, default to true
No value provided for grantSecretReadAccess, default to true
Using region: us-east-1
Applying layers to Lambda functions...
Using Node Lambda layer: arn:aws:lambda:us-east-1:464622532012:layer:Datadog-Node18-x:102
Generating construct Id for Datadog Lambda layer
Adding layer staging-aster-EventsStack/DatadogLayer-nodejs18.x-791ed699c5e1f177b63a98e804d08929694d2c6c523610390fe844ddfda7944b to Lambda: ${Token[TOKEN.1364]}
Using extension layer: arn:aws:lambda:us-east-1:464622532012:layer:Datadog-Extension-ARM:51
Generating construct Id for Datadog Extension layer
Adding layer staging-aster-EventsStack/DatadogExtension-791ed699c5e1f177b63a98e804d08929694d2c6c523610390fe844ddfda7944b to Lambda: ${Token[TOKEN.1364]}
Using Node Lambda layer: arn:aws:lambda:us-east-1:464622532012:layer:Datadog-Node18-x:102
Generating construct Id for Datadog Lambda layer
Adding layer staging-aster-EventsStack/DatadogLayer-nodejs18.x-791ed699c5e1f177b63a98e804d08929694d2c6c523610390fe844ddfda7944b to Lambda: ${Token[TOKEN.1404]}
Using extension layer: arn:aws:lambda:us-east-1:464622532012:layer:Datadog-Extension-ARM:51
Generating construct Id for Datadog Extension layer
Adding layer staging-aster-EventsStack/DatadogExtension-791ed699c5e1f177b63a98e804d08929694d2c6c523610390fe844ddfda7944b to Lambda: ${Token[TOKEN.1404]}
Using Node Lambda layer: arn:aws:lambda:us-east-1:464622532012:layer:Datadog-Node18-x:102
Generating construct Id for Datadog Lambda layer
Adding layer staging-aster-EventsStack/DatadogLayer-nodejs18.x-791ed699c5e1f177b63a98e804d08929694d2c6c523610390fe844ddfda7944b to Lambda: ${Token[TOKEN.1440]}
Using extension layer: arn:aws:lambda:us-east-1:464622532012:layer:Datadog-Extension-ARM:51
Generating construct Id for Datadog Extension layer
Adding layer staging-aster-EventsStack/DatadogExtension-791ed699c5e1f177b63a98e804d08929694d2c6c523610390fe844ddfda7944b to Lambda: ${Token[TOKEN.1440]}
Using Node Lambda layer: arn:aws:lambda:us-east-1:464622532012:layer:Datadog-Node18-x:102
Generating construct Id for Datadog Lambda layer
Adding layer staging-aster-EventsStack/DatadogLayer-nodejs18.x-791ed699c5e1f177b63a98e804d08929694d2c6c523610390fe844ddfda7944b to Lambda: ${Token[TOKEN.1476]}
Using extension layer: arn:aws:lambda:us-east-1:464622532012:layer:Datadog-Extension-ARM:51
Generating construct Id for Datadog Extension layer
Adding layer staging-aster-EventsStack/DatadogExtension-791ed699c5e1f177b63a98e804d08929694d2c6c523610390fe844ddfda7944b to Lambda: ${Token[TOKEN.1476]}
Using Node Lambda layer: arn:aws:lambda:us-east-1:464622532012:layer:Datadog-Node18-x:102
Generating construct Id for Datadog Lambda layer
Adding layer staging-aster-EventsStack/DatadogLayer-nodejs18.x-791ed699c5e1f177b63a98e804d08929694d2c6c523610390fe844ddfda7944b to Lambda: ${Token[TOKEN.1512]}
Using extension layer: arn:aws:lambda:us-east-1:464622532012:layer:Datadog-Extension-ARM:51
Generating construct Id for Datadog Extension layer
Adding layer staging-aster-EventsStack/DatadogExtension-791ed699c5e1f177b63a98e804d08929694d2c6c523610390fe844ddfda7944b to Lambda: ${Token[TOKEN.1512]}
Using Node Lambda layer: arn:aws:lambda:us-east-1:464622532012:layer:Datadog-Node18-x:102
Generating construct Id for Datadog Lambda layer
Adding layer staging-aster-EventsStack/DatadogLayer-nodejs18.x-791ed699c5e1f177b63a98e804d08929694d2c6c523610390fe844ddfda7944b to Lambda: ${Token[TOKEN.1548]}
Using extension layer: arn:aws:lambda:us-east-1:464622532012:layer:Datadog-Extension-ARM:51
Generating construct Id for Datadog Extension layer
Adding layer staging-aster-EventsStack/DatadogExtension-791ed699c5e1f177b63a98e804d08929694d2c6c523610390fe844ddfda7944b to Lambda: ${Token[TOKEN.1548]}
Using Node Lambda layer: arn:aws:lambda:us-east-1:464622532012:layer:Datadog-Node18-x:102
Generating construct Id for Datadog Lambda layer
Adding layer staging-aster-EventsStack/DatadogLayer-nodejs18.x-791ed699c5e1f177b63a98e804d08929694d2c6c523610390fe844ddfda7944b to Lambda: ${Token[TOKEN.1584]}
Using extension layer: arn:aws:lambda:us-east-1:464622532012:layer:Datadog-Extension-ARM:51
Generating construct Id for Datadog Extension layer
Adding layer staging-aster-EventsStack/DatadogExtension-791ed699c5e1f177b63a98e804d08929694d2c6c523610390fe844ddfda7944b to Lambda: ${Token[TOKEN.1584]}
Using Node Lambda layer: arn:aws:lambda:us-east-1:464622532012:layer:Datadog-Node18-x:102
Generating construct Id for Datadog Lambda layer
Adding layer staging-aster-EventsStack/DatadogLayer-nodejs18.x-791ed699c5e1f177b63a98e804d08929694d2c6c523610390fe844ddfda7944b to Lambda: ${Token[TOKEN.1620]}
Using extension layer: arn:aws:lambda:us-east-1:464622532012:layer:Datadog-Extension-ARM:51
Generating construct Id for Datadog Extension layer
Adding layer staging-aster-EventsStack/DatadogExtension-791ed699c5e1f177b63a98e804d08929694d2c6c523610390fe844ddfda7944b to Lambda: ${Token[TOKEN.1620]}
Using Node Lambda layer: arn:aws:lambda:us-east-1:464622532012:layer:Datadog-Node18-x:102
Generating construct Id for Datadog Lambda layer
Adding layer staging-aster-EventsStack/DatadogLayer-nodejs18.x-791ed699c5e1f177b63a98e804d08929694d2c6c523610390fe844ddfda7944b to Lambda: ${Token[TOKEN.1656]}
Using extension layer: arn:aws:lambda:us-east-1:464622532012:layer:Datadog-Extension-ARM:51
Generating construct Id for Datadog Extension layer
Adding layer staging-aster-EventsStack/DatadogExtension-791ed699c5e1f177b63a98e804d08929694d2c6c523610390fe844ddfda7944b to Lambda: ${Token[TOKEN.1656]}
Using Node Lambda layer: arn:aws:lambda:us-east-1:464622532012:layer:Datadog-Node18-x:102
Generating construct Id for Datadog Lambda layer
Adding layer staging-aster-EventsStack/DatadogLayer-nodejs18.x-791ed699c5e1f177b63a98e804d08929694d2c6c523610390fe844ddfda7944b to Lambda: ${Token[TOKEN.1692]}
Using extension layer: arn:aws:lambda:us-east-1:464622532012:layer:Datadog-Extension-ARM:51
Generating construct Id for Datadog Extension layer
Adding layer staging-aster-EventsStack/DatadogExtension-791ed699c5e1f177b63a98e804d08929694d2c6c523610390fe844ddfda7944b to Lambda: ${Token[TOKEN.1692]}
Using Node Lambda layer: arn:aws:lambda:us-east-1:464622532012:layer:Datadog-Node18-x:102
Generating construct Id for Datadog Lambda layer
Adding layer staging-aster-EventsStack/DatadogLayer-nodejs18.x-791ed699c5e1f177b63a98e804d08929694d2c6c523610390fe844ddfda7944b to Lambda: ${Token[TOKEN.1728]}
Using extension layer: arn:aws:lambda:us-east-1:464622532012:layer:Datadog-Extension-ARM:51
Generating construct Id for Datadog Extension layer
Adding layer staging-aster-EventsStack/DatadogExtension-791ed699c5e1f177b63a98e804d08929694d2c6c523610390fe844ddfda7944b to Lambda: ${Token[TOKEN.1728]}
Using Node Lambda layer: arn:aws:lambda:us-east-1:464622532012:layer:Datadog-Node18-x:102
Generating construct Id for Datadog Lambda layer
Adding layer staging-aster-EventsStack/DatadogLayer-nodejs18.x-791ed699c5e1f177b63a98e804d08929694d2c6c523610390fe844ddfda7944b to Lambda: ${Token[TOKEN.1764]}
Using extension layer: arn:aws:lambda:us-east-1:464622532012:layer:Datadog-Extension-ARM:51
Generating construct Id for Datadog Extension layer
Adding layer staging-aster-EventsStack/DatadogExtension-791ed699c5e1f177b63a98e804d08929694d2c6c523610390fe844ddfda7944b to Lambda: ${Token[TOKEN.1764]}
Using Node Lambda layer: arn:aws:lambda:us-east-1:464622532012:layer:Datadog-Node18-x:102
Generating construct Id for Datadog Lambda layer
Adding layer staging-aster-EventsStack/DatadogLayer-nodejs18.x-791ed699c5e1f177b63a98e804d08929694d2c6c523610390fe844ddfda7944b to Lambda: ${Token[TOKEN.1800]}
Using extension layer: arn:aws:lambda:us-east-1:464622532012:layer:Datadog-Extension-ARM:51
Generating construct Id for Datadog Extension layer
Adding layer staging-aster-EventsStack/DatadogExtension-791ed699c5e1f177b63a98e804d08929694d2c6c523610390fe844ddfda7944b to Lambda: ${Token[TOKEN.1800]}
Using Node Lambda layer: arn:aws:lambda:us-east-1:464622532012:layer:Datadog-Node18-x:102
Generating construct Id for Datadog Lambda layer
Adding layer staging-aster-EventsStack/DatadogLayer-nodejs18.x-791ed699c5e1f177b63a98e804d08929694d2c6c523610390fe844ddfda7944b to Lambda: ${Token[TOKEN.1836]}
Using extension layer: arn:aws:lambda:us-east-1:464622532012:layer:Datadog-Extension-ARM:51
Generating construct Id for Datadog Extension layer
Adding layer staging-aster-EventsStack/DatadogExtension-791ed699c5e1f177b63a98e804d08929694d2c6c523610390fe844ddfda7944b to Lambda: ${Token[TOKEN.1836]}
Using Node Lambda layer: arn:aws:lambda:us-east-1:464622532012:layer:Datadog-Node18-x:102
Generating construct Id for Datadog Lambda layer
Adding layer staging-aster-EventsStack/DatadogLayer-nodejs18.x-791ed699c5e1f177b63a98e804d08929694d2c6c523610390fe844ddfda7944b to Lambda: ${Token[TOKEN.1872]}
Using extension layer: arn:aws:lambda:us-east-1:464622532012:layer:Datadog-Extension-ARM:51
Generating construct Id for Datadog Extension layer
Adding layer staging-aster-EventsStack/DatadogExtension-791ed699c5e1f177b63a98e804d08929694d2c6c523610390fe844ddfda7944b to Lambda: ${Token[TOKEN.1872]}
Using Node Lambda layer: arn:aws:lambda:us-east-1:464622532012:layer:Datadog-Node18-x:102
Generating construct Id for Datadog Lambda layer
Adding layer staging-aster-EventsStack/DatadogLayer-nodejs18.x-791ed699c5e1f177b63a98e804d08929694d2c6c523610390fe844ddfda7944b to Lambda: ${Token[TOKEN.1908]}
Using extension layer: arn:aws:lambda:us-east-1:464622532012:layer:Datadog-Extension-ARM:51
Generating construct Id for Datadog Extension layer
Adding layer staging-aster-EventsStack/DatadogExtension-791ed699c5e1f177b63a98e804d08929694d2c6c523610390fe844ddfda7944b to Lambda: ${Token[TOKEN.1908]}
Using Node Lambda layer: arn:aws:lambda:us-east-1:464622532012:layer:Datadog-Node18-x:102
Generating construct Id for Datadog Lambda layer
Adding layer staging-aster-EventsStack/DatadogLayer-nodejs18.x-791ed699c5e1f177b63a98e804d08929694d2c6c523610390fe844ddfda7944b to Lambda: ${Token[TOKEN.1944]}
Using extension layer: arn:aws:lambda:us-east-1:464622532012:layer:Datadog-Extension-ARM:51
Generating construct Id for Datadog Extension layer
Adding layer staging-aster-EventsStack/DatadogExtension-791ed699c5e1f177b63a98e804d08929694d2c6c523610390fe844ddfda7944b to Lambda: ${Token[TOKEN.1944]}
Using Node Lambda layer: arn:aws:lambda:us-east-1:464622532012:layer:Datadog-Node18-x:102
Generating construct Id for Datadog Lambda layer
Adding layer staging-aster-EventsStack/DatadogLayer-nodejs18.x-791ed699c5e1f177b63a98e804d08929694d2c6c523610390fe844ddfda7944b to Lambda: ${Token[TOKEN.1980]}
Using extension layer: arn:aws:lambda:us-east-1:464622532012:layer:Datadog-Extension-ARM:51
Generating construct Id for Datadog Extension layer
Adding layer staging-aster-EventsStack/DatadogExtension-791ed699c5e1f177b63a98e804d08929694d2c6c523610390fe844ddfda7944b to Lambda: ${Token[TOKEN.1980]}
Using Node Lambda layer: arn:aws:lambda:us-east-1:464622532012:layer:Datadog-Node18-x:102
Generating construct Id for Datadog Lambda layer
Adding layer staging-aster-EventsStack/DatadogLayer-nodejs18.x-791ed699c5e1f177b63a98e804d08929694d2c6c523610390fe844ddfda7944b to Lambda: ${Token[TOKEN.2016]}
Using extension layer: arn:aws:lambda:us-east-1:464622532012:layer:Datadog-Extension-ARM:51
Generating construct Id for Datadog Extension layer
Adding layer staging-aster-EventsStack/DatadogExtension-791ed699c5e1f177b63a98e804d08929694d2c6c523610390fe844ddfda7944b to Lambda: ${Token[TOKEN.2016]}
Using Node Lambda layer: arn:aws:lambda:us-east-1:464622532012:layer:Datadog-Node18-x:102
Generating construct Id for Datadog Lambda layer
Adding layer staging-aster-EventsStack/DatadogLayer-nodejs18.x-791ed699c5e1f177b63a98e804d08929694d2c6c523610390fe844ddfda7944b to Lambda: ${Token[TOKEN.2052]}
Using extension layer: arn:aws:lambda:us-east-1:464622532012:layer:Datadog-Extension-ARM:51
Generating construct Id for Datadog Extension layer
Adding layer staging-aster-EventsStack/DatadogExtension-791ed699c5e1f177b63a98e804d08929694d2c6c523610390fe844ddfda7944b to Lambda: ${Token[TOKEN.2052]}
Using Node Lambda layer: arn:aws:lambda:us-east-1:464622532012:layer:Datadog-Node18-x:102
Generating construct Id for Datadog Lambda layer
Adding layer staging-aster-EventsStack/DatadogLayer-nodejs18.x-791ed699c5e1f177b63a98e804d08929694d2c6c523610390fe844ddfda7944b to Lambda: ${Token[TOKEN.2088]}
Using extension layer: arn:aws:lambda:us-east-1:464622532012:layer:Datadog-Extension-ARM:51
Generating construct Id for Datadog Extension layer
Adding layer staging-aster-EventsStack/DatadogExtension-791ed699c5e1f177b63a98e804d08929694d2c6c523610390fe844ddfda7944b to Lambda: ${Token[TOKEN.2088]}
Using Node Lambda layer: arn:aws:lambda:us-east-1:464622532012:layer:Datadog-Node18-x:102
Generating construct Id for Datadog Lambda layer
Adding layer staging-aster-EventsStack/DatadogLayer-nodejs18.x-791ed699c5e1f177b63a98e804d08929694d2c6c523610390fe844ddfda7944b to Lambda: ${Token[TOKEN.2124]}
Using extension layer: arn:aws:lambda:us-east-1:464622532012:layer:Datadog-Extension-ARM:51
Generating construct Id for Datadog Extension layer
Adding layer staging-aster-EventsStack/DatadogExtension-791ed699c5e1f177b63a98e804d08929694d2c6c523610390fe844ddfda7944b to Lambda: ${Token[TOKEN.2124]}
Wrapping Lambda function handlers with Datadog handler...
Forwarder ARN not provided, no log group subscriptions will be added
Adding CDK Construct version tag: 1.10.0
Setting environment variables...
Adding datadog tags
Setting Datadog transport environment variables...
Adding source code integration...
Validating props...
No value provided for flushMetricsToLogs, defaulting to true
Using extension version 51, metrics will be submitted via the extension
No value provided for addLayers, defaulting to true
No value provided for enableDatadogTracing, defaulting to true
No value provided for enableDatadogASM, defaulting to false
No value provided for enableMergeXrayTraces, defaulting to false
No value provided for injectLogContext, defaulting to true
No value provided for logLevel
No value provided for enableDatadogLogs, defaulting to true
No value provided for captureLambdaPayload, default to false
No value provided for sourceCodeIntegration, default to true
No value provided for redirectHandler, default to true
No value provided for grantSecretReadAccess, default to true
Using region: us-east-1
Applying layers to Lambda functions...
Using Node Lambda layer: arn:aws:lambda:us-east-1:464622532012:layer:Datadog-Node18-x:102
Generating construct Id for Datadog Lambda layer
Adding layer staging-aster-EventsStack/DatadogLayer-nodejs18.x-791ed699c5e1f177b63a98e804d08929694d2c6c523610390fe844ddfda7944b to Lambda: ${Token[TOKEN.2296]}
Using extension layer: arn:aws:lambda:us-east-1:464622532012:layer:Datadog-Extension-ARM:51
Generating construct Id for Datadog Extension layer
Adding layer staging-aster-EventsStack/DatadogExtension-791ed699c5e1f177b63a98e804d08929694d2c6c523610390fe844ddfda7944b to Lambda: ${Token[TOKEN.2296]}
Using Node Lambda layer: arn:aws:lambda:us-east-1:464622532012:layer:Datadog-Node18-x:102
Generating construct Id for Datadog Lambda layer
Adding layer staging-aster-EventsStack/DatadogLayer-nodejs18.x-791ed699c5e1f177b63a98e804d08929694d2c6c523610390fe844ddfda7944b to Lambda: ${Token[TOKEN.2321]}
Using extension layer: arn:aws:lambda:us-east-1:464622532012:layer:Datadog-Extension-ARM:51
Generating construct Id for Datadog Extension layer
Adding layer staging-aster-EventsStack/DatadogExtension-791ed699c5e1f177b63a98e804d08929694d2c6c523610390fe844ddfda7944b to Lambda: ${Token[TOKEN.2321]}
Wrapping Lambda function handlers with Datadog handler...
Forwarder ARN not provided, no log group subscriptions will be added
Adding CDK Construct version tag: 1.10.0
Setting environment variables...
Adding datadog tags
Setting Datadog transport environment variables...
Adding source code integration...
  ```

**Comment by nacho-vazquez** [comment] 2023-12-13 12:43
I can also see the layers applied to the Lambda on AWS
![IMG_7009](https://github.com/DataDog/datadog-cdk-constructs/assets/149403662/922b7dd6-d2a1-4ca7-b806-47e96754f5f0)

**Comment by sfirrin** [comment] 2023-12-20 15:13
Hey @nacho-vazquez thank you for opening this and sorry for the issues

It does look like everything is configured correctly with the layers, so my suspicion would be that there is something with the environment variables going wrong. The best way to debug further would be to contact our support team https://www.datadoghq.com/support/ so we can collect more information about your configuration and track down the cause

**Comment by nacho-vazquez** [comment] 2023-12-20 15:15
Thank you! I will try to reproduce this issue in an isolated project to give better information to the support team.

For now, I drop the CDK, and I'm setting DD on the CI/CD using the console.

**Comment by sfirrin** [comment] 2023-12-20 15:37
OK sounds good. You might also want to check out the datadog-ci lambda instrument command https://github.com/DataDog/datadog-ci/tree/master/src/commands/lambda#readme as another option

**Comment by nacho-vazquez** [comment] 2023-12-20 16:15
Yes, that's precisely what I'm using; I mistype. Thank you!

**Comment by sfirrin** [comment] 2023-12-20 16:40
:+1: I'm going to close this out, please get in touch again if you run into anything else

**Closed by sfirrin** 2023-12-20 16:40 UTC
